apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keygen-config
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "basic.labels" . | indent 4 }}
data:
  KEYGEN_ACCOUNT_ID: {{ .Values.keygen.config.accountId | default uuidv4 }}
  KEYGEN_HOST: {{ .Values.keygen.config.apiHost }}
  {{- with .Values.postgres }}
  {{- $dbService := (printf "%s-keygen-postgres-service" $.Release.Name) }}
  {{- $dbUrl := (printf "postgres://%s:%s@%s.%s.svc.cluster.local:%d/%s" .credentials.username .credentials.password $dbService $.Release.Namespace (.port | int) .defaultDb ) }}
  DATABASE_URL: {{ $dbUrl }}
  {{- end }}
  {{- with .Values.redis }}
  {{- $redisService := (printf "%s-keygen-redis-service" $.Release.Name) }}
  {{- $redisUrl := (printf "redis://%s.%s.svc.cluster.local:%d" $redisService $.Release.Namespace (.port | int) ) }}
  REDIS_URL: {{ $redisUrl }}
  {{- end }}
