apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keygen-secrets
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "basic.labels" . | indent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
type: Opaque
data:
  ADMIN_EMAIL: {{ .Values.keygen.secret.adminEmail | b64enc }}
  ADMIN_PASSWORD: {{ .Values.keygen.secret.adminPassword | default "ailabs1337tw" | b64enc }}
  SECRET_KEY_BASE: {{ .Values.keygen.secret.secretKeyBase | default (randAlphaNum 64) | b64enc }}
  ENCRYPTION_DETERMINISTIC_KEY: {{ .Values.keygen.secret.encryptionDeterministicKey | default (randAlphaNum 32) | b64enc }}
  ENCRYPTION_PRIMARY_KEY: {{ .Values.keygen.secret.encryptionPrimaryKey | default (randAlphaNum 32) | b64enc }}
  ENCRYPTION_KEY_DERIVATION_SALT: {{ .Values.keygen.secret.encryptionKeyDerivationSalt | default (randAlphaNum 32) | b64enc }}
