apiVersion: v1
kind: Namespace
metadata:
  name: builtin-infra
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asr-redis-pvc
  namespace: builtin-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-redis-deployment
  namespace: builtin-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asr-redis
  template:
    metadata:
      labels:
        app: asr-redis
    spec:
      containers:
        - name: asr-redis
          image: redis:6.2.13-alpine3.18
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: asr-redis-persistent-storage
              mountPath: /data
      volumes:
        - name: asr-redis-persistent-storage
          persistentVolumeClaim:
            claimName: asr-redis-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keygen-postgres-pvc
  namespace: builtin-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keygen-postgres-deployment
  namespace: builtin-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keygen-postgres
  template:
    metadata:
      labels:
        app: keygen-postgres
    spec:
      containers:
        - name: keygen-postgres
          image: postgres:12.15-alpine3.18
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: keygen-postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: keygen-postgres-persistent-storage
          persistentVolumeClaim:
            claimName: keygen-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: asr-redis-service
  namespace: builtin-infra
spec:
  selector:
    app: asr-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: keygen-postgres-service
  namespace: builtin-infra
spec:
  selector:
    app: keygen-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
