apiVersion: v1
kind: Secret
metadata:
  name: keygen-secrets
  namespace: builtin-infra
type: Opaque
data:
  ADMIN_EMAIL: bm8tcmVwbHlAYWlsYWJzLnR3
  ADMIN_PASSWORD: RUtkZVhOVEF3bkhSU0Z0azVNNGZlMDdkZ0twWXgrZHpxNXpvdExCa3JrRT0=
  SECRET_KEY_BASE: N2JiMGM1NjViZWUxZjZmNWMwNjk4ODBmNjBmZWMwZmJhMzFlZWM2Y2E1Y2MzZDgwYTcyOTViMzM2MTEzMzg2MDNjZjNkYjZlYzU3MDVhNWFiZGU1ZmI1NGVjM2Q0MjVjYTMwYmZlY2U1ZWQzMjUxMWYzMDM5MjlhZDJlMzFlYmE=
  ENCRYPTION_DETERMINISTIC_KEY: OGRYN1Y4ZGNBR3JMRWZLdEdpZVk1U0dDWWdkRjU1NmhhcUtDM2JhcWNMOD0=
  ENCRYPTION_PRIMARY_KEY: Ti9LaVA3WXRaVVVxSU9CUWxQL1dEaS9iSVVORVFXZkJ0QXp4UFBnL1dUYTI2NUk9
  ENCRYPTION_KEY_DERIVATION_SALT: ZjFRRGdkRFRMUmtySzBBQXFSWVQrZ0tGTVBWT0MvM2pQTHBveVJFVFlnPQ==
